In [1]:
#1. What is a Python library? Why ^o we use Python libraries?

In [2]:
"""python libraray are numpy and pandas which is used to perform mathametical operation and for visualisation"""

'python libraray are numpy and pandas which is used to perform mathametical operation and for visualisation'

In [4]:
#2. What is the difference between Numpy array and List?

In [5]:
"""array contain homogenious data where list contain hetrogenoeuos data"""

'array contain homogenious data where list contain hetrogenoeuos data'

In [24]:
#3. Find the shape, size and dimension of the following array?[[1, 2, 3, 4][5, 6, 7, 8],[9, 10, 11, 12]]

In [25]:
import numpy as np

In [26]:
arr1 = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [27]:
np.shape(arr1)

(3, 4)

In [28]:
np.size(arr1)

12

In [29]:
arr = np.array(arr1)

In [30]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
np.ndim(arr)

2

In [84]:
#4. Write python code to access the first row of the following array?[[1, 2, 3, 4].[5, 6, 7, 8],[9, 10, 11, 12]]

In [33]:
l = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [35]:
arr3= np.array(l)

In [36]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr3[0]

array([1, 2, 3, 4])

In [85]:
#5. How do you access the element at the third row and fourth column from the given numpy array?[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [39]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr3[2]

array([ 9, 10, 11, 12])

In [48]:
arr3[:, -1]

array([ 4,  8, 12])

In [86]:
6. Write code to extract all odd-indexed elements from the given numpy array?[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

SyntaxError: invalid syntax (3141854106.py, line 1)

In [49]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:

arr3[arr3 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [51]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [52]:
arr1=np.random.randint(0,1,(3,3))

In [53]:
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

In [55]:
'''numpy.random.rand in the init function, rather than the numpy.random.randn function as shown in the original.'''

'numpy.random.rand in the init function, rather than the numpy.random.randn function as shown in the original.'

In [ ]:
#9. Write code to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [56]:
b= np.expand_dims(arr3, axis=0) 
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
#10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [57]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
arr3.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
#11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [59]:
import numpy.matlib as nm

In [64]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [65]:
result = np.multiply(A, B)

In [66]:
result

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [68]:
A/B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
A-B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [71]:
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
#12. Which function in Numpy can be used to swap the byte order of an array?

In [73]:
'''byteswap()'''

'byteswap()'

In [74]:
#13. What is the significance of the np.linalg.inv function?

In [78]:
'''used to find the inverse of matrix'''

'used to find the inverse of matrix'

In [79]:
#14. What does the np.reshape function do, and how is it use^?

In [80]:
"""to change the dimension"""

'to change the dimension'

In [82]:
#15. What is broadcasting in Numpy?

In [83]:
'''doing some opertion in each element'''

'doing some opertion in each element'